services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:9999
    networks:
      - payment-processor
  payment-processor-1:
    image: zanfranceschi/payment-processor
    networks:
      - payment-processor
    hostname: payment-processor-default
    ports:
      - 8001:8080
  payment-processor-2:
    image: zanfranceschi/payment-processor
    networks:
      - payment-processor
    hostname: payment-processor-fallback
    ports:
      - 8002:8080

networks:
  payment-processor:
    name: payment-processor
    driver: bridge